// Generated by CoffeeScript 1.7.1
var $;

$ = require('fj-config');

$.remBase = 16;

exports.lowerBound = function(range) {
  if (range.length <= 0) {
    return 0;
  }
  return range[0];
};

exports.upperBound = function(range) {
  if (range.length < 2) {
    return 999999999999;
  }
  return range[1];
};

exports.stripUnit = function(num) {
  return parseFloat(num);
};

exports.convertToRem = function(value, baseValue) {
  if (baseValue == null) {
    baseValue = $.remBase;
  }
  value = stripUnit(value) / stripUnit(baseValue);
  if (value !== 0) {
    value = value + 'rem';
  }
  return value;
};

exports.data = function(attr) {
  var ns;
  if ((ns = $.namespace)) {
    return '[data-' + ns + '-' + attr + ']';
  } else {
    return '[data-' + attr + ']';
  }
};

exports.remCalc = function(values, baseValue) {
  if (baseValue == null) {
    baseValue = $.remBase;
  }
  if (values.length === 1) {
    return convertToRem(values[0], baseValue);
  }
  return values.map(function(value) {
    return convertToRem(value, baseValue);
  });
};

exports.rgba = function(hex, opacity) {
  var b, g, r;
  hex = hex.replace('#', '');
  r = parseInt(hex.substring(0, 2), 16);
  g = parseInt(hex.substring(2, 4), 16);
  b = parseInt(hex.substring(4, 6), 16);
  return 'rgba(' + r + ',' + g + ',' + b + ',' + opacity + ')';
};
